#!/bin/bash -e

function configure_elasticsearch
{
    echo -ne "\n" && ctx logger info "Deleting events index if exists..." && \
    curl --silent --retry 5 --retry-delay 3 -XDELETE http://localhost:9200/cloudify_events/ && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating events index..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_events -d '{"settings": {"analysis": {"analyzer": {"default": {"tokenizer": "whitespace"}}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Deleting index if exists..." && \
    curl --silent --silent --retry 5 --retry-delay 3 -XDELETE http://localhost:9200/cloudify_storage && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating index..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage -d '{"settings": {"analysis": {"analyzer": {"default": {"tokenizer": "whitespace"}}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating blueprint mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/blueprint/_mapping -d '{"blueprint": {"properties": {"plan": {"enabled": false}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating deployment mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/deployment/_mapping -d '{"deployment": {"properties": {"workflows": {"enabled": false}, "inputs": {"enabled": false}, "policy_type": {"enabled": false}, "policy_triggers": {"enabled": false}, "groups": {"enabled": false}, "outputs": {"enabled": false}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating node mapping..." && \
    curl --fail --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node/_mapping -d '{ "node": { "_id": { "path": "id" }, "properties": { "types": { "type": "string", "index_name": "type" }, "properties": { "enabled": false }, "operations": { "enabled": false }, "relationships": { "enabled": false } } } }' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating node-instance mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node_instance/_mapping -d '{ "node_instance": { "_id": { "path": "id" }, "properties": { "runtime_properties": { "enabled": false } } } }' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating deployment-modifications mapping..." && \
    curl --fail --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/deployment_modification/_mapping -d '{ "deployment_modification": { "_id": { "path": "id" }, "properties": { "modified_nodes": { "enabled": false }, "node_instances": { "enabled": false }, "context": { "enabled": false } } } }' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Printing mappings..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XGET http://localhost:9200/cloudify_storage/_mapping?pretty=1
}