#!/bin/bash -e

# ES_HOST="localhost"
# ES_PORT="9200"

# function log() {
#     message=$1

#     echo -ne "\n" && ctx logger info "${message}"
# }

# function post() {
#     params=$1
#     fail=$2

#     ctx logger info "curling ${params}"
#     if [ ! -z $fail ]; then
#         curl --fail --retry 5 --retry-delay 3 $params && echo -ne "\n"
#     else
#         curl --retry 5 --retry-delay 3 $params && echo -ne "\n"
#     fi
# }

# function configure_elasticsearch() {
#     log "Deleting events index if exists..." && \
#     post "-XDELETE http://${ES_HOST}:9200/cloudify_events/" && \
#     log "Creating events index..." && \
#     post "-XPUT http://${ES_HOST}:${ES_PORT}/cloudify_events -d '{\"settings\": {\"analysis\": {\"analyzer\": {\"default\": {\"tokenizer\": \"whitespace\"}}}}}'" "fail" && \
#     log "Deleting index if exists..." && \
#     post "-XDELETE http://${ES_HOST}:${ES_PORT}/cloudify_storage" && \
#     log "Creating index..." && \
#     post "-XPUT http://${ES_HOST}:${ES_PORT}/cloudify_storage -d '{\"settings\": {\"analysis\": {\"analyzer\": {\"default\": {\"tokenizer\": \"whitespace\"}}}}}'" "fail" && \
#     log "Creating blueprint mapping..." && \
#     post "-XPUT http://${ES_HOST}:${ES_PORT}/cloudify_storage/blueprint/_mapping -d '{\"blueprint\": {\"properties\": {\"plan\": {\"enabled\": false}}}}'" "fail" && \
#     log "Creating deployment mapping..." && \
#     post "-XPUT http://${ES_HOST}:${ES_PORT}/cloudify_storage/deployment/_mapping -d '{\"deployment\": {\"properties\": {\"workflows\": {\"enabled\": false}, \"inputs\": {\"enabled\": false}, \"policy_type\": {\"enabled\": false}, \"policy_triggers\": {\"enabled\": false}, \"groups\": {\"enabled\": false}, \"outputs\": {\"enabled\": false}}}}'" "fail" && \
#     log "Creating node mapping..." && \
#     post "-XPUT http://${ES_HOST}:${ES_PORT}/cloudify_storage/node/_mapping -d '{ \"node\": { \"_id\": { \"path\": \"id\" }, \"properties\": { \"types\": { \"type\": \"string\", \"index_name\": \"type\" }, \"properties\": { \"enabled\": false }, \"operations\": { \"enabled\": false }, \"relationships\": { \"enabled\": false } } } }'" "fail" && \
#     log "Creating node-instance mapping..." && \
#     post "-XPUT http://${ES_HOST}:${ES_PORT}/cloudify_storage/node_instance/_mapping -d '{ \"node_instance\": { \"_id\": { \"path\": \"id\" }, \"properties\": { \"runtime_properties\": { \"enabled\": false } } } }'" "fail" && \
#     log "Creating deployment-modifications mapping..." && \
#     post "-XPUT http://${ES_HOST}:${ES_PORT}/cloudify_storage/deployment_modification/_mapping -d '{ \"deployment_modification\": { \"_id\": { \"path\": \"id\" }, \"properties\": { \"modified_nodes\": { \"enabled\": false }, \"node_instances\": { \"enabled\": false }, \"context\": { \"enabled\": false } } } }'" "fail"
# }

 function configure_elasticsearch() {
    # echo -ne "\n" && ctx logger info "Deleting events index if exists..." && \
    # curl --silent --retry 5 --retry-delay 3 -XDELETE http://localhost:9200/cloudify_events/ && echo -ne "\n" && \
    # echo -ne "\n" && ctx logger info "Deleting index if exists..." && \
    # curl --silent --retry 5 --retry-delay 3 -XDELETE http://localhost:9200/cloudify_storage && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating events index..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_events -d '{"settings": {"analysis": {"analyzer": {"default": {"tokenizer": "whitespace"}}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating index..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage -d '{"settings": {"analysis": {"analyzer": {"default": {"tokenizer": "whitespace"}}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating blueprint mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/blueprint/_mapping -d '{"blueprint": {"properties": {"plan": {"enabled": false}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating deployment mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/deployment/_mapping -d '{"deployment": {"properties": {"workflows": {"enabled": false}, "inputs": {"enabled": false}, "policy_type": {"enabled": false}, "policy_triggers": {"enabled": false}, "groups": {"enabled": false}, "outputs": {"enabled": false}}}}' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating node mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node/_mapping -d '{ "node": { "_id": { "path": "id" }, "properties": { "types": { "type": "string", "index_name": "type" }, "properties": { "enabled": false }, "operations": { "enabled": false }, "relationships": { "enabled": false } } } }' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating node-instance mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node_instance/_mapping -d '{ "node_instance": { "_id": { "path": "id" }, "properties": { "runtime_properties": { "enabled": false } } } }' && echo -ne "\n" && \
    echo -ne "\n" && ctx logger info "Creating deployment-modifications mapping..." && \
    curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/deployment_modification/_mapping -d '{ "deployment_modification": { "_id": { "path": "id" }, "properties": { "modified_nodes": { "enabled": false }, "node_instances": { "enabled": false }, "context": { "enabled": false } } } }' && echo -ne "\n"
 }
