#!/bin/bash -e

function sys_error
{
    ctx logger error "${1:-UNKNOWN} (status $?)"
    # ctx logger error "${1:-UNKNOWN} (status $?)"
    exit 1
}

# DEPRECATED
function log
{
    level=$1
    message=$2
    timestamp=$(date +"%Y-%m-%dT%T%z")

    echo "### ${timestamp}, ${level}: ${message}"
}

function create_virtualenv
{
    virtualenv_path=$1

    ctx logger info "Creating virtualenv ${virtualenv_path}..."
    sudo virtualenv ${virtualenv_path}
}

function create_dir
{
    dir=$1

    ctx logger info "Creating directory ${dir}..."
    sudo mkdir -p ${dir}
}

function install_module
{
    module=$1
    venv=${2:-""}

    if [[ ! -z "${venv}" ]]; then
        ctx logger info "Installing ${module} in virtualenv ${venv}..."
        sudo ${venv}/bin/pip install ${module} >/dev/null
    else
        ctx logger info "Installing ${module}..."
        sudo pip install ${module} >/dev/null
    fi
}


function install_rpm
{
    source=$1
    if [[ -z "${source}" ]]; then
        sys_error "Must supply url as param (install_rpm #URL#)."
    fi

    # ctx logger info "Installing RPM ${tmp_file_path}..."
    # sudo yum install -y ${source}

    tmp_file_path="/tmp/${RANDOM}.rpm"
    download_file ${source} ${tmp_file_path}
    ctx logger info "Installing RPM ${tmp_file_path}..."
    sudo rpm --nodeps -ivh ${tmp_file_path}
    clean_tmp
}

function clean_tmp
{
    ctx logger info "Cleaning up /tmp..."
    sudo rm -rf /tmp/*
}

function download_file
{
    url=$1
    destination_path=$2

    set +e
    curl_cmd=$(which curl)
    wget_cmd=$(which wget)
    set -e

    if [[ -z ${destination_path} ]]; then
        ctx logger info "Downloading ${url}..."
        destination_path="/tmp/${RANDOM}.file"
    else
        ctx logger info "Downloading ${url} to ${destination_path}..."
    fi
    if [[ ! -z ${curl_cmd} ]]; then
        curl --fail --silent --location ${url} --create-dirs -o ${destination_path} >/dev/null
    elif [[ ! -z ${wget_cmd} ]]; then
        wget -O ${destination_path} ${url} >/dev/null
    else
        sys_error "Failed to download ${url}: Neither 'cURL' nor 'wget' were found on the system"
    fi
    echo ${destination_path}
}

function check_empty_var
{
    var=$1
    message=$2

    if [[ -z "${var}" ]]; then
        sys_error "${message}"
    fi
}

function copy_notice
{
    service=$1

    destination_notice="/opt/${service}_NOTICE.txt"
    ctx logger info "Copying ${service} NOTICE file to ${destination_notice}..."
    notice_file=$(ctx download-resource "components/${service}/NOTICE.txt")
    sudo mv ${notice_file} ${destination_notice}
}

function wait_for_port
{
    c=0
    while ! echo exit | curl http://localhost:$1;
    do
            if [[ $c -gt 24 ]]; then
                sys_error "Failed to connect to service... (status $?)"
            fi
            echo "host not up yet... retrying... ($c/24)"
            sleep 5;
            c=$((c+1))
    done
}

function yum_install
{
    source=$1

    ctx logger info "yum Installing ${source}..."
    sudo yum install -y ${source} >/dev/null
}