#!/bin/bash -e

function configure_influxdb() {
    INFLUXDB_HOST=$1
    INFLUXDB_PORT=$2
    DB_USER="root"
    DB_PASS="root"
    DB_NAME="cloudify"

    ctx logger info "Creating InfluxDB Database..."
    sudo curl --show-error --silent --retry 5 "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}/db?u=${DB_USER}&p=${DB_PASS}" -d "{\"name\": \"${DB_NAME}\"}"
    test_db_creation=$(curl --show-error --silent --retry 5 "http://${INFLUXDB_HOST}:${INFLUXDB_PORT}/cluster_admins?u=${DB_USER}&p=${DB_PASS}")
    ctx logger info "InfluxDB Database Creation test: ${test_db_creation}"
}
